### ISSUE TITLE
Realistic "Sandbags"

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#10]
Make the current sandbags more realistic by making it possible to create sandbags from any ground soil, dirt, grass, sand etc. 

Reference: https://www.quora.com/Do-sandbags-play-an-important-role-in-modern-warfare-given-that-they-have-been-in-use-since-WW1-Is-there-an-alternative-that-can-replace-sandbags/answer/Daryl-Tew?srid=uNzPp

**Comment by DarkGuardsman** [comment]
Ya that was always the plan, and I removed the current ones we had in the mod. They didn't look very good for the style. If we re-implement them we need to not use funky 3D models no matter how much work went into the model. Instead we should take time to make models that fit Minecraft and make sure to have non-model versions. For example we can use the same model for the cobblestone wall to make sandbags.
