### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by mb03minecrafter** [BuiltBrokenModding/MilitaryBaseDecor#12]
Hey where is the download for this mod? I don't really care if it is still in dev because I am trying to make a volts replacement modpack.

**Comment by mb03minecrafter** [comment]
I know this is still being worked on, but I kind of want to help make this mod if that is okay.

**Comment by DarkGuardsman** [comment]
Your welcome to contribute to the project at any time, and right now we don't have any dev versions to release. The mod still needs a bit of work before it can be released. Mainly adding recipes, fixing textures, and removing unfinished content that is no longer needed.
