### ISSUE TITLE
Adding barber wire fence top

### ISSUE THREAD

**Issue by mb03minecrafter** [BuiltBrokenModding/MilitaryBaseDecor#13]
I came up with this texture for the top of the barbed wire fencing. It is based on the barbed_wire_fence texture, I think this would be a good addition since I didn't see a file that indicated it was the top of the barbed wire fence.
![barbed_wired_fence_top](https://cloud.githubusercontent.com/assets/13096082/17268111/f75cdd56-55e4-11e6-91f8-a81b929dd771.png)

**Comment by mb03minecrafter** [comment]
![barbed_wired_fence_top](https://cloud.githubusercontent.com/assets/13096082/17268130/e37d1304-55e5-11e6-8d70-5b6d4341a192.png)
Actually this one looks better

**Comment by DarkGuardsman** [comment]
I'll see if it works in game later this weekend or next week

**Comment by mb03minecrafter** [comment]
Ok thanks! I am helping because I am really excited about this mod!

**Comment by mb03minecrafter** [comment]
Also how do I build the project in Eclipse?(if I even can build it)

**Comment by DarkGuardsman** [comment]
There is actually a script, dev.bat, in the BuiltBrokenScript folder that comes with the project. It will do most of the work for the setup but the eclipse side of the script doesn't always work right. Normally everyone just uses intelliji IDEA for the projects. If I get time later I'll make video on how to setup the eclipse project for all of our mods. However, right now I'm heading off to sleep for a few hours before going back to freelance projects.

**Comment by mb03minecrafter** [comment]
k. I have a mac but whatevs. I hope we an stay in contact since this is actually my first time ever messing with mods. GN

**Comment by mb03minecrafter** [comment]
OMG I HAD NO IDEA BUT DID YOU MAKE ICBM?!!!

**Comment by DarkGuardsman** [comment]
yes along with 100+ other mods and modpacks

**Comment by dmodoomsirius** [comment]
I haven't had the time to set up a Linux build/dev script. when I get the time that is on my todo list. tho for mac its on ./gradlew <insert commands here> its similar for Linux.

**Comment by mb03minecrafter** [comment]
Also how hard would it be to update Atomic Science(NOT RESONANT INDUCTION) to 1.7.10?

**Comment by DarkGuardsman** [comment]
It is not hard but will take a bit of time. Right now we are updating MFFS which will be another month before we can even test. Atomic Science will take 3-4 months to get updated and ready for use.

**Comment by mb03minecrafter** [comment]
Well just know that I am in on all of it. I hope to bring the original volts back. Or at least that is my end goal. It would be nice if you could give me somewhere to go to learn how to do this stuff since I haven't programmed in Java in forever. I have only done Unity C# for the past year, but no java. Thanks!

**Comment by mb03minecrafter** [comment]
Plus it seems like I have a lot more time than y'all

**Comment by Hennamann** [comment]
For Java it self there are plenty of youtube tutorials,  for minecraft i'd recommend pahimars modding series. Once you feel you are ready to work on MilitaryBaseDecor check the issues that are still open and this gist checklist: https://gist.github.com/Hennamann/4a019bf7b3b778882eab it might be a bit outdated but it's a start. If you have any more questions feel free to ask me or darkguardsman.

**Comment by Hennamann** [comment]
Closing this, seeing as how it may be difficult to implement a top texture for the barbed wire fence in it's current state.
