### ISSUE TITLE
Change recipe system

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#19]
Move most if not all recipes from the way they are now, to IRecipeContainer methods in the correct blocks and item classes.

**Comment by DarkGuardsman** [comment]
We might be switching to a property system using JSON soon if you are willing to wait. https://github.com/BuiltBrokenModding/VoltzEngine/issues/66

**Comment by Hennamann** [comment]
Hmmm, any ETA on that? Might just wait, seeing as how there is a minuscule amount of recipes that need moving. and it's not confusing, yet.

**Comment by DarkGuardsman** [comment]
I'm hoping to get it done in the next week or two so I can start porting mods over to 1.8+

**Comment by Hennamann** [comment]
Sounds good. I'll probably just wait then, JSON FTW!

**Comment by Hennamann** [comment]
This is now irrelevant as the work on the 1.12 rewrite has begun.
