### ISSUE TITLE
Server crashes when using wire cutters

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#20]
Upon using wire cutters on any type of wired fence in survival, the server crashes with a nosuchmethoderror. Probably due to a reference to non-server code. 

Notably the crash does not occur in creative mode.

**Comment by DarkGuardsman** [comment]
Crash would be useful but your most likely right.

**Comment by Hennamann** [comment]
https://gist.github.com/Hennamann/c13151ec76aed78c6f2f1adf0fcc2d9a

**Comment by DarkGuardsman** [comment]
Block.getItem(World, int, int, int) is a client side only method

https://github.com/BuiltBrokenModding/MilitaryBaseDecor/blob/master/src/main/java/com/builtbroken/militarybasedecor/modules/worldwar1/content/block/BlockWireFence.java#L94

**Comment by Hennamann** [comment]
Yup noticed that as well, changing it to Item.getitemfromblock instead, just need to work metadata into it.

**Comment by DarkGuardsman** [comment]
no, just pass in 'this'. The ItemStack constructor can take a block as a param.

**Comment by Hennamann** [comment]
That's true, I'll test it and then commit the changes
