### ISSUE TITLE
Add more reinforced rail types

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#25]
Add reinforced rail equivalents to vanilla rails like Powered rails, Detector rails, and activator rails

**Comment by DarkGuardsman** [comment]
Sure, that should be simple to do but we also still need to fix water breaking reinforced rails

**Comment by Hennamann** [comment]
Hmmm, didn't know that was a thing, I'll look into it.

**Comment by DarkGuardsman** [comment]
It might be something I have to fix as it will require modifying base code using ASM

**Comment by Hennamann** [comment]
No longer relevant
