### ISSUE TITLE
Please update to 1.12.2 - I have a military enthusiast

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BuiltBrokenModding/MilitaryBaseDecor#29]
Thank you for your time. Make sure mod is server friendly.

**Comment by Hennamann** [comment]
The mod will be updated to 1.12.2 eventually. For the time being the plan is to finish some underlying changes to the 1.7.10 version and then start work on getting the mod updated to 1.12.2.

As for being server friendly, I hope to make most things configurable to suit everyone's needs but feel free to make some examples of how I could make the mod, even more, server friendly.
