### ISSUE TITLE
Create a smarter recipe system

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#3]
We have two options for the recipe system in mbd:
1. Disable certain blocks if it requires blocks/items from another module to create it, to do this we should check what modules are loaded.
2. Create a system with that contains more than one recipe, where it disables and enables the different recipes depending on what modules is being loaded. 

We can also create both of these systems, and then add a config option for which one to use, that way the player has a lot more control over the way recipes work. Feel free to suggest improvements and other ways to implement recipes into mbd!

**Comment by DarkGuardsman** [comment]
3rd option is better, by default we want the second option to load. This way we are always linking the modules together. While at the same time allowing for the modules to be disabled. 

Also at no time should we ever disable a block automatically. It should always be done by the user's doing this way a world doesn't mistakenly lose blocks.
