### ISSUE TITLE
Add more ammo crates and new functionality

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#30]
The old Ammunition Boxes and Equipment crates have been brought back to the rewrite. But I hope to add more variations and brand new crates to the mod. Along with some limited chest functionality with configurations options.

**Comment by DarkGuardsman** [comment]
**Reminder:** Use block states, feed from an enum of render types, that stores data in a TileEntity. 
If we do it this way we can simply automate the process of adding new inventory containers. Simply by adding an entry to the enum and then adding render JSONs.

Also, make sure the inventory size is configurable. By default, if the box is roughly the size of a chest it should have the same inventory of a chest. Users who do not like this can change the size via the configs. 

Remember this is a decoration mod and not a gameplay mod. So everything should match vanilla unless it doesn't feel right. For example, doing a half-sized box then it would feel correct to do half inventory size. Same if we do a 2 block tall weapon locker having a larger inventory.

How to code the GUI, write some simple scale code that draws slots from left to right top to bottom. With a scroll bar that can be added later on for super large inventories. Though for the moment we can limit the max size to our limited GUI size.

**Comment by Hennamann** [comment]
I'm considering this closed with commits: 3556794 and 16b09efb36ae7d6211a7af06ae03a289eaa7bcc0 more changes and improvements are needed but it's good enough for the upcoming alpha release.
