### ISSUE TITLE
Add concrete

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#31]
I want to add concrete but I want to drop the 5 different tiers of concrete we had before as it made things confusing. I hope to have a single tier that aims to be a step up from the vanilla one, along with the Classic ICBM concrete as well.
- [ ] New Strong Concrete

**Comment by DarkGuardsman** [comment]
Honestly, you can skip the ICBM CLassic concrete.... I really do not think anyone will miss it.
