### ISSUE TITLE
Reimplement Blastcraft content

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#35]
Get all the content from Blastcraft and add it to Military Base Decor again, possibly add some more improvements and new features along the way.

- [ ] Blastproof Blocks/Walling
- [ ] Hardened Bricks
- [ ] Blast Compressor
- [ ] Carbon Plated Walling

**Comment by DarkGuardsman** [comment]
Why again are we keeping blastcraft content? I do not remember at all the reason.

**Comment by Hennamann** [comment]
I always liked the mod and remade it, but when I joined the team I didn't have time to maintain it whilst working on MBD so I merged it with Military Base Decor. I could separate it into its own mod again, as I don't think I'll be doing too many changes and I have more time to maintain it now. I don't want the mod to die again though.

**Comment by DarkGuardsman** [comment]
Ah, I remember now, it's fine if it stays. I was just trying to think of why we included it to start with. Though that doesn't matter as it does fit with our goal to provide decorations.
