### ISSUE TITLE
Kind of taking a break

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#4]
Why post this here? i had no other place to post it p;

I have been and am still taking a small break from minecraft modding, i will return sometime before/after christmas to finish militarybasedecor and begin work on other projects, but for now i won't be updating anything. I'm still online though, so feel free to send me an email, send me a message on skype if you have me there etc. 
But yeah, militarybasedecor will be finished, mark my word.

**Comment by DarkGuardsman** [comment]
Should be no issue, your welcome to work or not work at your own pace. Anyways next time your on IRC bug me for my contact info. That way you can email me if you have concerns or issues.

**Comment by DarkGuardsman** [comment]
@Hennamann I need your curse name/id so I can give you credit correctly. I'm pushing forward with setting up the project, and will be buffing out issues with the mod this week. Trying to get everything released so ICBM has a concrete mod to be downloaded with.

**Comment by Hennamann** [comment]
@DarkGuardsman Hennamann99

**Comment by Hennamann** [comment]
Or actually, that might be wrong... not sure, here´s a link to my curseforge profile: http://minecraft.curseforge.com/members/Hennamann just in case
