### ISSUE TITLE
Junit testing

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/MilitaryBaseDecor#5]
We should add junit testing to MBD so we can make sure somethings work properly when compiling.

**Comment by DarkGuardsman** [comment]
Yes, though only complex blocks will need JUnit testing. Most of the blocks are very basic and can be handled with automated block placement tests.

**Comment by Hennamann** [comment]
I've never setup JUnit before though. Do we have any documentation or examples on it?

**Comment by dmodoomsirius** [comment]
Look at ve src/test that will help you tho dark can explain it better then I can.

**Comment by Hennamann** [comment]
I see, I'l probably figure it out.

**Comment by Hennamann** [comment]
Work on this has now begun with commit: 8b483fc. It still needs a lot more work to provide a high coverage percent.

**Comment by Hennamann** [comment]
Closing as it's no longer relevant.
