### ISSUE TITLE
In-game documentation

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/MilitaryBaseDecor#6]
MilitaryBaseDecor should have in game documentation for explaingin example usages for blocks, recipes and give some background on the blocks(what they are used for IRL). Should take form in a book. Should use the planned VE ingame documentation feature.

**Comment by DarkGuardsman** [comment]
Most likely the planned VE ingame documentation will be nicer looking then a book. Think full screen GUI with better text parsing and support of html.

**Comment by Hennamann** [comment]
Closing as work on the wiki has begun, and will hopefully be implemented soon.
