### ISSUE TITLE
Suggestion: customizable alarms

### ISSUE THREAD

**Issue by robthegray** [BuiltBrokenModding/MilitaryBaseDecor#7]
if the mod adds alarms could a system be implemented that allows players to add their own sounds?

**Comment by DarkGuardsman** [comment]
I actually have another mod I'm working on to implement this feature. Its called 'addicted to red' which adds several ways to emit sound. Including replicate sound effects from mobs, machines, and other sources. Alarms would be an easy addition to the existing framework.

**Comment by robthegray** [comment]
cool, If you need a model the klaxon in this pic from the titan missile museum would look good.

![image](https://cloud.githubusercontent.com/assets/16519903/13506483/55f6a6c0-e14c-11e5-87b4-6f4aac100a3f.png)

**Comment by Hennamann** [comment]
Closing, as this suggestion is no longer related to Military Base Decor
