### ISSUE TITLE
reinforced button

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/MilitaryBaseDecor#9]
Ability to have a reinforced button so it can't be blown off.

**Comment by DarkGuardsman** [comment]
oh I see you're working on the mod again Hennamann. When you get a chance join IRC so we can go over the plan for the mod. This way I can express a few ideas that me and dmod have been going over.

**Comment by Hennamann** [comment]
I'l log onto IRC sometime after Wednesday next week, as i'm away from home until then.
